development: &development
  adapter: postgresql
  host: localhost
  username: postgres
  password: not_blank
  encoding: UTF8
  min_messages: warning
  database: skyrim_dev

test: &test
  <<: *development
  database: skyrim_test

production:
  <<: *development
  database: skyrim_production
